language: haxe

haxe:
    - development
    - "3.4.7"
    - "3.2.1"

install:
    - haxelib install hxcpp

script:
    - haxelib dev jsoni18n .
    - cd tests
    - haxe -main Main -lib jsoni18n -cpp build
    - cd build
    - ./Main
