language: haxe

haxe:
    - "3.4.0"
    - "3.2.1"

os:
    - linux
    - osx

install:
    - haxelib install hxcpp

script:
    - haxelib dev jsoni18n .
    - cd tests
    - haxe -main Main -lib jsoni18n -cpp build
    - cd build
    - ./Main
