language: haxe

haxe:
    - "4.0.0-rc.2"
    - "3.4.7"
    - "3.4.6"

install:
    - haxelib install hxcpp

script:
    - haxelib dev jsoni18n .
    - cd tests
    - haxe -main Main -lib jsoni18n -cpp build
    - cd build
    - ./Main
